planning_time_limit: 10.0
max_iterations: 20
max_iterations_after_collision_free: 0
smoothness_cost_weight: 0.5
obstacle_cost_weight: 0.5
learning_rate: 0.01
smoothness_cost_velocity: 0.5
smoothness_cost_acceleration: 0.5
smoothness_cost_jerk: 0.0
ridge_factor: 0.0
use_pseudo_inverse: false
pseudo_inverse_ridge_factor: 1e-4
joint_update_limit: 0.1
collision_clearence: 0.2
collision_threshold: 0.07
use_stochastic_descent: false
enable_failure_recovery: false
max_recovery_attempts: 5
trajectory_initialization_method: "quintic-spline"